# Generated by Django 3.0.4 on 2021-03-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210323_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='comp_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vac_id',
            field=models.IntegerField(null=True),
        ),
    ]
