# Generated by Django 3.0.4 on 2021-03-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210323_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='comp_id',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='vac_id',
        ),
    ]
