# Generated by Django 3.0.4 on 2021-04-06 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20210406_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('NS', 'Не ищу работу'), ('OP', 'Рассматриваю предложения'), ('SE', 'Ищу работу')], max_length=10)),
                ('salary', models.PositiveIntegerField()),
                ('specialty', models.CharField(choices=[('BG', 'Стажер'), ('JN', 'Джуниор'), ('MD', 'Миддл'), ('SEN', 'Синьор'), ('LE', 'Лид')], max_length=10)),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('portfolio', models.CharField(max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
