# Generated by Django 3.0.4 on 2021-04-08 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='grade',
            field=models.CharField(blank=True, choices=[('BG', 'Стажер'), ('JN', 'Джуниор'), ('MD', 'Миддл'), ('SEN', 'Синьор'), ('LE', 'Лид')], max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='specialty',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_specialty', to='main.Specialty'),
        ),
    ]
