# Generated by Django 3.0.4 on 2021-04-08 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210408_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.CharField(choices=[('BG', 'Стажер'), ('JN', 'Джуниор'), ('MD', 'Миддл'), ('SEN', 'Синьор'), ('LE', 'Лид')], max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_vacancy', to='main.Specialty'),
        ),
    ]
