# Generated by Django 3.0.4 on 2021-04-09 08:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210409_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
