# Generated by Django 3.0.4 on 2021-04-09 08:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210409_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=tinymce.models.HTMLField(),
        ),
    ]
